=== unboxed/bops/engines/bops_api/schemas/odp/v0.7.7/public/show.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "application": {
      "$ref": "#/definitions/ApplicationOverview"
    },
    "property": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "latitude": {
              "type": "number"
            },
            "longitude": {
              "type": "number"
            },
            "title": {
              "type": "string"
            },
            "singleLine": {
              "type": "string"
            },
            "uprn": {
              "type": "string"
            },
            "town": {
              "type": "string"
            },
            "postcode": {
              "type": "string"
            }
          },
          "required": [
            "latitude",
            "longitude",
            "title",
            "singleLine",
            "uprn",
            "town",
            "postcode"
          ]
        },
        "boundary": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "site": {}
          },
          "required": ["site"]
        }
      },
      "required": ["address", "boundary"]
    },
    "proposal": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string"
        },
        "reportingType": {
          "anyOf": [
            {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "code": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                }
              },
              "required": ["code", "description"]
            },
            {
              "type": "null"
            }
          ]
        },
        "ownerIsPlanningAuthority": {
          "type": "boolean"
        }
      },
      "required": [
        "description",
        "ownerIsPlanningAuthority",
        "reportingType"
      ]
    },
    "applicant": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "anyOf": [{ "type": "string" }, { "type": "null" }]
        },
        "address": {
          "anyOf": [
            {
              "$ref": "#/definitions/Address"
            },
            { "type": "null" }
          ]
        },
        "ownership": {
          "anyOf": [
            {
              "$ref": "#/definitions/Ownership"
            },
            { "type": "null" }
          ]
        },
        "agent": {
          "anyOf": [
            {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "address": {
                  "anyOf": [
                    {
                      "$ref": "#/definitions/Address"
                    },
                    { "type": "null" }
                  ]
                }
              }
            },
            { "type": "null" }
          ]
        }
      },
      "required": ["type", "address", "ownership", "agent"]
    },
    "officer": {
      "anyOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "name": {
              "type": "string"
            }
          },
          "required": ["name"]
        },
        {
          "type": "null"
        }
      ]
    },
    "data": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "appeal": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "reason": {
              "type": "string"
            },
            "lodgedDate": {
              "type": "string",
              "format": "date"
            },
            "validatedDate": {
              "type": "string",
              "format": "date"
            },
            "startedDate": {
              "type": "string",
              "format": "date"
            },
            "decisionDate": {
              "type": "string",
              "format": "date"
            },
            "decision": {
              "type": "string"
            },
            "files": {
              "type": "array",
              "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "referencesInDocument": {
                    "type": "array",
                    "items": {
                      "type": "array"
                    }
                  },
                  "url": {
                    "type": "string"
                  },
                  "type": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "value": {
                          "type": "string"
                        },
                        "description": {
                          "type": "string"
                        }
                      },
                      "required": ["value", "description"]
                    }
                  },
                  "createdAt": {
                    "format": "datetime",
                    "type": ["string", "null"]
                  },
                  "applicantDescription": {
                    "type": ["string", "null"]
                  },
                  "metadata": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "byteSize": {
                        "type": "number"
                      },
                      "contentType": {
                        "type": "string"
                      }
                    },
                    "required": ["byteSize", "contentType"]
                  }
                },
                "required": ["name", "url", "type", "metadata"]
              }
            }
          }
        }
      }
    }
  },
  "required": ["application", "property", "proposal", "applicant"]
}

=== unboxed/bops/engines/bops_api/spec/fixtures/examples/odp/v0.7.7/public/show.json
{
  "application": {
    "type": { "value": "pa.part1.classA", "description": "prior_approval" },
    "reference": "25-00240-PA1A",
    "fullReference": "SWK-25-00240-PA1A",
    "targetDate": "2025-04-08",
    "expiryDate": "2025-03-25",
    "receivedAt": "2025-03-04T14:36:32.999+00:00",
    "validAt": "2025-03-04T00:00:00.000+00:00",
    "publishedAt": "2025-03-06T14:22:12.293+00:00",
    "determinedAt": null,
    "determinationDate": null,
    "decision": null,
    "status": "Appeal allowed",
    "consultation": {
      "startDate": null,
      "endDate": null,
      "publicUrl": "https://southwark.bops-applicants.localhost:3001/planning_applications/25-00240-PA1A",
      "publishedComments": [],
      "consulteeComments": []
    },
    "pressNotice": null
  },
  "property": {
    "address": {
      "latitude": 22.87483014329466,
      "longitude": 105.04327269762632,
      "title": "7796 Sherie Mountain",
      "singleLine": "7796 Sherie Mountain, Bashirianland, 78923",
      "uprn": "00254420",
      "town": "Bashirianland",
      "postcode": "78923"
    },
    "boundary": { "site": null }
  },
  "proposal": {
    "description": "Non voluptatum quo et.",
    "reportingType": null,
    "ownerIsPlanningAuthority": false
  },
  "applicant": {
    "type": null,
    "address": null,
    "ownership": null,
    "agent": { "address": null }
  },
  "officer": { "name": "Zena Spinka" },
  "data": {
    "appeal": {
      "reason": "too slow!",
      "lodgedDate": "2025-02-26",
      "validatedDate": "2025-02-27",
      "startedDate": "2025-02-28",
      "decisionDate": "2025-03-02",
      "decision": "allowed",
      "files": [
        {
          "name": "01_decision_type_counts.png",
          "url": "/files/b48as3tuafybda00zffy1h8ym0mu",
          "type": [
            {
              "value": "internal.appealDecision",
              "description": "Appeal Decision"
            }
          ],
          "createdAt": "2025-03-06T20:42:18.299+00:00",
          "applicantDescription": null,
          "metadata": { "byteSize": 312599, "contentType": "image/png" }
        },
        {
          "name": "03_average_days_to_decision.png",
          "url": "/files/93dj4n9hw8px6q1wgnm7hqwjwyu7",
          "type": [
            {
              "value": "internal.appealDecision",
              "description": "Appeal Decision"
            }
          ],
          "createdAt": "2025-03-06T20:42:18.400+00:00",
          "applicantDescription": null,
          "metadata": { "byteSize": 338776, "contentType": "image/png" }
        },
        {
          "name": "02_decision_by_app_type.png",
          "url": "/files/n2jd2xor3sl8514m49a4rn8rf3p4",
          "type": [
            {
              "value": "internal.appealDecision",
              "description": "Appeal Decision"
            }
          ],
          "createdAt": "2025-03-06T20:42:18.415+00:00",
          "applicantDescription": null,
          "metadata": { "byteSize": 890308, "contentType": "image/png" }
        },
        {
          "name": "04_applications_without_decision.png",
          "url": "/files/gd21huup5zg82wl4qy38gia2tapx",
          "type": [
            {
              "value": "internal.appealDecision",
              "description": "Appeal Decision"
            }
          ],
          "createdAt": "2025-03-06T20:42:18.428+00:00",
          "applicantDescription": null,
          "metadata": { "byteSize": 258315, "contentType": "image/png" }
        }
      ]
    }
  }
}
