=== unboxed/bops/engines/bops_api/schemas/odp/v0.7.7/show.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "agent_first_name": { "type": ["string", "null"] },
    "agent_last_name": { "type": ["string", "null"] },
    "agent_phone": { "type": ["string", "null"] },
    "agent_email": { "type": ["string", "null"] },
    "agent_company_name": { "type": ["string", "null"] },
    "agent_address_1": { "type": ["string", "null"] },
    "agent_address_2": { "type": ["string", "null"] },
    "agent_town": { "type": ["string", "null"] },
    "agent_county": { "type": ["string", "null"] },
    "agent_postcode": { "type": ["string", "null"] },
    "applicant_first_name": { "type": ["string", "null"] },
    "applicant_last_name": { "type": ["string", "null"] },
    "applicant_phone": { "type": ["string", "null"] },
    "applicant_email": { "type": ["string", "null"] },
    "applicant_address_1": { "type": ["string", "null"] },
    "applicant_address_2": { "type": ["string", "null"] },
    "applicant_town": { "type": ["string", "null"] },
    "applicant_county": { "type": ["string", "null"] },
    "applicant_postcode": { "type": ["string", "null"] },
    "user_role": { "type": ["string", "null"] },
    "awaiting_determination_at": { "type": ["string", "null"] },
    "to_be_reviewed_at": { "type": ["string", "null"] },
    "created_at": { "type": "string" },
    "description": { "type": ["string", "null"] },
    "determined_at": { "type": ["string", "null"] },
    "determination_date": { "type": ["string", "null"] },
    "id": { "type": "integer" },
    "invalidated_at": { "type": ["string", "null"] },
    "in_assessment_at": { "type": ["string", "null"] },
    "payment_reference": { "type": ["string", "null"] },
    "payment_amount": { "type": ["string", "null"] },
    "alternative_reference": { "type": ["string", "null"] },
    "result_flag": { "type": ["string", "null"] },
    "result_heading": { "type": ["string", "null"] },
    "result_description": { "type": ["string", "null"] },
    "result_override": { "type": ["string", "null"] },
    "returned_at": { "type": ["string", "null"] },
    "started_at": { "type": ["string", "null"] },
    "status": { "type": "string" },
    "target_date": { "type": ["string", "null"] },
    "withdrawn_at": { "type": ["string", "null"] },
    "work_status": { "type": ["string", "null"] },
    "boundary_geojson": {},
    "assigned_user_name": { "type": "string" },
    "assigned_user_role": { "type": "string" },
    "ownership_certificate": { "type": "string" },
    "application_type": { "type": "string" },
    "reference": { "type": "string" },
    "reference_in_full": { "type": "string" },
    "site": {
      "type": "object",
      "properties": {
        "address_1": { "type": ["string", "null"] },
        "address_2": { "type": ["string", "null"] },
        "county": { "type": ["string", "null"] },
        "town": { "type": ["string", "null"] },
        "postcode": { "type": ["string", "null"] },
        "uprn": { "type": ["string", "null"] },
        "latitude": { "type": ["number", "null"] },
        "longitude": { "type": ["number", "null"] }
      },
      "required": ["address_1", "address_2", "county", "town", "postcode", "uprn", "latitude", "longitude"]
    },
    "received_date": { "type": ["string", "null"] },
    "validAt": { "type": ["string", "null"] },
    "publishedAt": { "type": ["string", "null"] },
    "decision": { "type": "string" },
    "constraints": {
      "type": "array",
      "items": { "type": "string" }
    },
    "documents": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "url": { "type": "string" },
          "created_at": { "type": ["string", "null"] },
          "tags": {
            "type": "array",
            "items": { "type": "string" }
          },
          "numbers": { "type": ["string", "null"] },
          "applicant_description": { "type": ["string", "null"] }
        },
        "required": ["url"]
      }
    },
    "published_comments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "comment": { "type": ["string", "null"] },
          "received_at": { "type": ["string", "null"] },
          "summary_tag": { "type": ["string", "null"] }
        },
        "required": ["comment", "received_at", "summary_tag"]
      }
    },
    "consultee_comments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "comment": { "type": ["string", "null"] },
          "received_at": { "type": ["string", "null"] }
        },
        "required": ["comment", "received_at"]
      }
    },
    "consultation": {
      "type": "object",
      "properties": {
        "end_date": { "type": ["string", "null"] }
      },
      "required": ["end_date"]
    },
    "make_public": { "type": "boolean" }
  },
  "required": [
    "id",
    "status",
    "created_at",
    "description",
    "application_type",
    "reference",
    "reference_in_full",
    "site",
    "make_public"
  ]
}

=== unboxed/bops/engines/bops_api/spec/fixtures/examples/odp/v0.7.7/show.json
{
  "agent_first_name": "Jennifer",
  "agent_last_name": "Harper",
  "agent_phone": "2378788894",
  "agent_email": "agent@example.com",
  "agent_company_name": null,
  "agent_address_1": null,
  "agent_address_2": null,
  "agent_town": null,
  "agent_county": null,
  "agent_postcode": null,
  "applicant_first_name": "Albert",
  "applicant_last_name": "Manteras",
  "applicant_email": "albert@example.com",
  "applicant_phone": "01232223333",
  "applicant_address_1": null,
  "applicant_address_2": null,
  "applicant_town": null,
  "applicant_county": null,
  "applicant_postcode": null,
  "user_role": "agent",
  "awaiting_determination_at": null,
  "to_be_reviewed_at": null,
  "created_at": "2023-05-23T09:39:04.197+01:00",
  "description": "A single storey ground floor rear extension",
  "determined_at": null,
  "determination_date": "2024-03-06",
  "id": 2,
  "invalidated_at": null,
  "in_assessment_at": null,
  "payment_reference": "PAY1",
  "payment_amount": "0.0",
  "alternative_reference": null,
  "result_flag": "Planning permission / Permission needed",
  "result_heading": "It looks like these changes will need planning permission",
  "result_description": "Based on the information you have provided, we do not think this is eligible for a Lawful Development Certificate",
  "result_override": "This was my reason for rejecting the result",
  "returned_at": null,
  "started_at": null,
  "status": "not_started",
  "target_date": "2023-06-27",
  "withdrawn_at": null,
  "work_status": "proposed",
  "boundary_geojson": {
    "type": "Feature",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [-0.07716178894042969, 51.50094238217541],
          [-0.07645905017852783, 51.50053497847238],
          [-0.07615327835083008, 51.50115276135022],
          [-0.07716178894042969, 51.50094238217541]
        ]
      ]
    }
  },
  "assigned_user_name": "Keva Daugherty",
  "assigned_user_role": "reviewer",
  "application_type": "prior_approval",
  "reference": "23-00101-LDCP",
  "reference_in_full": "SWK-23-00101-LDCP",
  "site": {
    "address_1": "11 Abbey Gardens",
    "address_2": "",
    "county": "",
    "town": "WOODMANSTERNE ROAD, LONDON",
    "postcode": "SE16 3RQ",
    "uprn": "100081043511",
    "latitude": 51.4842536,
    "longitude": -0.0764165
  },
  "received_date": "2023-05-23T00:00:00.000+01:00",
  "documents": [],
  "published_comments": [],
  "consultee_comments": [],
  "consultation": {
    "end_date": "2023-08-21"
  },
  "make_public": false
}

=== unboxed/bops/engines/bops_api/spec/fixtures/examples/planning_applications/show.json
{
  "agent_first_name": "Jennifer",
  "agent_last_name": "Harper",
  "agent_phone": "2378788894",
  "agent_email": "agent@example.coms",
  "applicant_first_name": "Albert",
  "applicant_last_name": "Manteras",
  "applicant_email": "albert@example.com",
  "applicant_phone": "01232223333",
  "user_role": "agent",
  "awaiting_determination_at": null,
  "to_be_reviewed_at": null,
  "created_at": "2023-05-23T09:39:04.197+01:00",
  "description": "This is a long winded description, bla bla bla a single storey ground floor rear extension; replacement of existing garage door with brick infill and a new window; replacement of the existing windows with double glazed windows, installation of rooflight",
  "determined_at": null,
  "determination_date": "2024-03-06",
  "id": 2,
  "invalidated_at": null,
  "in_assessment_at": null,
  "payment_reference": "PAY1",
  "payment_amount": "0.0",
  "ownership_certificate": "A",
  "result_flag": "Planning permission / Permission needed",
  "result_heading": "It looks like these changes will need planning permission",
  "result_description": "Based on the information you have provided, we do not think this is eligible for a Lawful Development Certificate",
  "result_override": "This was my reason for rejecting the result",
  "returned_at": null,
  "started_at": null,
  "status": "not_started",
  "target_date": "2023-06-27",
  "withdrawn_at": null,
  "work_status": "proposed",
  "boundary_geojson": {
    "type": "Feature",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [
            -0.07716178894042969,
            51.50094238217541
          ],
          [
            -0.07645905017852783,
            51.50053497847238
          ],
          [
            -0.07615327835083008,
            51.50115276135022
          ],
          [
            -0.07716178894042969,
            51.50094238217541
          ]
        ]
      ]
    }
  },
  "assigned_user_name": "Keva Daugherty",
  "assigned_user_role": "reviewer",
  "application_type": "prior_approval",
  "reference": "23-00101-LDCP",
  "reference_in_full": "SWK-23-00101-LDCP",
  "site": {
    "address_1": "11 Abbey Gardens",
    "address_2": "",
    "county": "",
    "town": "WOODMANSTERNE ROAD, LONDON",
    "postcode": "SE16 3RQ",
    "uprn": "100081043511",
    "latitude": "51.4842536",
    "longitude": "-0.0764165"
  },
  "received_date": "2023-05-23T00:00:00.000+01:00",
  "constraints": [
    "Conservation area"
  ],
  "documents": [],
  "published_comments": [],
  "consultee_comments": [],
  "consultation": {
    "end_date": "2023-08-21"
  },
  "make_public": false
}
