=== unboxed/bops/engines/bops_api/schemas/odp/v0.7.6/documents.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "metadata": {
      "type": "object",
      "properties": {
        "results": {
          "type": "integer"
        },
        "totalResults": {
          "type": "integer"
        }
      },
      "required": ["results", "totalResults"]
    },
    "application": {
      "$ref": "#/definitions/ApplicationOverview"
    },
    "files": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "url": {
              "type": "string",
              "format": "url"
            },
            "type": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "value": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  }
                },
                "required": ["value", "description"]
              }
            },
            "createdAt": {
              "format": "datetime",
              "type": ["string", "null"]
            },
            "applicantDescription": {
              "type": ["string","null"]
            },
            "metadata": {
              "type": "object",
              "properties": {
                "byteSize": {
                  "type": "number"
                },
                "contentType": {
                  "type": "string"
                }
              },
              "required": ["byteSize", "contentType"]
            }
          },
          "required": ["name", "url", "type", "metadata"]
        }
      ]
    },
    "decisionNotice": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "required": ["name", "url"]
    }
  },
  "required": ["metadata", "application", "files"]
}

=== unboxed/bops/engines/bops_api/spec/fixtures/examples/odp/v0.7.0/documents.json
{
  "application": {
    "type": {
      "value": "pp.full.householder",
      "description": "planning_permission"
    },
    "reference": "24-00100-HAPP",
    "fullReference": "PlanX-24-00100-HAPP",
    "receivedAt": "2024-06-12T15:56:29.830+01:00",
    "validAt": "2024-06-12T00:00:00.000+01:00",
    "publishedAt": "2024-06-12T15:56:29.828+01:00",
    "determinedAt": null,
    "decision": null,
    "status": "determined",
    "consultation": {
      "startDate": "2024-04-15",
      "endDate": "2024-05-07"
    }
  },
  "files": [
    {
      "name": "proposed-floorplan.png",
      "url": "http://planx.example.com/api/v1/planning_applications/1889/documents/111",
      "type": [
        {
          "value": "elevations.proposed",
          "description": "Elevations - proposed"
        },
        {
          "value": "sections.proposed",
          "description": "Sections - proposed"
        }
      ],
      "createdAt": "2024-06-12T15:56:29.803+01:00",
      "applicantDescription": null,
      "metadata": {
        "byteSize": 144212,
        "contentType": "application/pdf"
      }
    },
    {
      "name": "site-notice.jpg",
      "url": "http://planx.example.com/api/v1/planning_applications/1889/documents/111",
      "type": [
        {
          "value": "internal.siteNotice",
          "description": "Site Notice"
        }
      ],
      "createdAt": "2024-06-12T15:56:29.803+01:00",
      "applicantDescription": null,
      "metadata": {
        "byteSize": 144212,
        "contentType": "application/pdf"
      }
    }
  ],
  "metadata": {
    "results": 1,
    "totalResults": 1
  },
  "decisionNotice": {
    "name": "decision-notice-PlanX-24-00100-HAPP.pdf",
    "url": "http://planx.example.com/api/v1/planning_applications/1889/decision_notice.pdf"
  }
}
